import os
from decouple import config
gettext = lambda s: s
DATA_DIR = os.path.dirname(os.path.dirname(__file__))
"""
Django settings for elevaweb project.

Generated by 'django-admin startproject' using Django 3.1.14.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
from pathlib import Path
BASE_DIR = Path(__file__).resolve().parent.parent
SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', default=False, cast=bool)
ALLOWED_HOSTS = []
ROOT_URLCONF = 'elevaweb.urls'
WSGI_APPLICATION = 'elevaweb.wsgi.application'
AUTH_PASSWORD_VALIDATORS = [{'NAME':
    'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'
    }, {'NAME':
    'django.contrib.auth.password_validation.MinimumLengthValidator'}, {
    'NAME':
    'django.contrib.auth.password_validation.CommonPasswordValidator'}, {
    'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'}
    ]
LANGUAGE_CODE = 'es'
TIME_ZONE = 'America/Santiago'
USE_I18N = True
USE_L10N = True
USE_TZ = True
STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(DATA_DIR, 'media')
STATIC_ROOT = os.path.join(DATA_DIR, 'static')
STATICFILES_DIRS = os.path.join(BASE_DIR, 'elevaweb', 'static'),
SITE_ID = 1
TEMPLATES = [{'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [os.path.join(BASE_DIR, 'elevaweb', 'templates')], 'OPTIONS': {
    'context_processors': ['django.contrib.auth.context_processors.auth',
    'django.contrib.messages.context_processors.messages',
    'django.template.context_processors.i18n',
    'django.template.context_processors.debug',
    'django.template.context_processors.request',
    'django.template.context_processors.media',
    'django.template.context_processors.csrf',
    'django.template.context_processors.tz',
    'sekizai.context_processors.sekizai',
    'django.template.context_processors.static',
    'cms.context_processors.cms_settings'], 'loaders': [
    'django.template.loaders.filesystem.Loader',
    'django.template.loaders.app_directories.Loader']}}]
MIDDLEWARE = ['cms.middleware.utils.ApphookReloadMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'cms.middleware.user.CurrentUserMiddleware',
    'cms.middleware.page.CurrentPageMiddleware',
    'cms.middleware.toolbar.ToolbarMiddleware',
    'cms.middleware.language.LanguageCookieMiddleware']

INSTALLED_APPS = ['djangocms_admin_style', 'django.contrib.auth',
    'django.contrib.contenttypes', 'django.contrib.sessions',
    'django.contrib.admin', 'django.contrib.sites',
    'django.contrib.sitemaps', 'django.contrib.staticfiles',
    'django.contrib.messages', 'cms', 'menus', 'sekizai', 'treebeard',
    'djangocms_text_ckeditor', 'filer', 'easy_thumbnails',
    'djangocms_bootstrap4',
    'djangocms_bootstrap4.contrib.bootstrap4_alerts',
    'djangocms_bootstrap4.contrib.bootstrap4_badge',
    'djangocms_bootstrap4.contrib.bootstrap4_card',
    'djangocms_bootstrap4.contrib.bootstrap4_carousel',
    'djangocms_bootstrap4.contrib.bootstrap4_collapse',
    'djangocms_bootstrap4.contrib.bootstrap4_content',
    'djangocms_bootstrap4.contrib.bootstrap4_grid',
    'djangocms_bootstrap4.contrib.bootstrap4_jumbotron',
    'djangocms_bootstrap4.contrib.bootstrap4_link',
    'djangocms_bootstrap4.contrib.bootstrap4_listgroup',
    'djangocms_bootstrap4.contrib.bootstrap4_media',
    'djangocms_bootstrap4.contrib.bootstrap4_picture',
    'djangocms_bootstrap4.contrib.bootstrap4_tabs',
    'djangocms_bootstrap4.contrib.bootstrap4_utilities', 'djangocms_file',
    'djangocms_icon', 'djangocms_link', 'djangocms_picture',
    'djangocms_style', 'djangocms_googlemap', 'djangocms_video',
    'djangocms_blog', 'elevaweb', 'blog', 'aldryn_apphooks_config',
    'parler', 'taggit', 'taggit_autosuggest', 'meta', 'sortedm2m']
LANGUAGES = ('es', gettext('Spanish')), ('en', gettext('English')), ('de',
    gettext('German'))
CMS_LANGUAGES = {(1): [{'code': 'es', 'name': gettext('Spanish'),
    'redirect_on_fallback': True, 'public': True, 'hide_untranslated': 
    False}, {'code': 'en', 'name': gettext('English'),
    'redirect_on_fallback': True, 'public': True, 'hide_untranslated': 
    False}, {'code': 'de', 'name': gettext('German'),
    'redirect_on_fallback': True, 'public': True, 'hide_untranslated': 
    False}], 'default': {'redirect_on_fallback': True, 'public': True,
    'hide_untranslated': False}}
CMS_TEMPLATES = ('fullwidth.html', 'Fullwidth'), ('sidebar_left.html',
    'Sidebar Left'), ('sidebar_right.html', 'Sidebar Right'), ('contact.html',
    'Contact'), ('index.html', 'Index')
X_FRAME_OPTIONS = 'SAMEORIGIN'
CMS_PERMISSION = True
CMS_PLACEHOLDER_CONF = {}
DATABASES = {
    'default': {
        'CONN_HEALTH_CHECKS': 'False',
        'CONN_MAX_AGE': 0,
        'ENGINE': config('DB_ENGINE'),
        'HOST': config('DB_HOST', default='localhost'),
        'NAME': config('DB_NAME'),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'PORT': config('DB_PORT', default=''),
        'USER': config('DB_USER', default=''),
    }
}

THUMBNAIL_PROCESSORS = ('easy_thumbnails.processors.colorspace',
    'easy_thumbnails.processors.autocrop',
    'filer.thumbnail_processors.scale_and_crop_with_subject_location',
    'easy_thumbnails.processors.filters')
APPEND_SLASH = False
PARLER_LANGUAGES = {(1): ({'code': 'es', 'fallbacks': ['en', 'de']}, {
    'code': 'en', 'fallbacks': ['es', 'de']}, {'code': 'de', 'fallbacks': [
    'es', 'en']}), 'default': {'fallbacks': ['es', 'en', 'de']}}
META_SITE_PROTOCOL = 'https'
META_USE_SITES = True
META_USE_OG_PROPERTIES = True
META_USE_TWITTER_PROPERTIES = True
META_USE_SCHEMAORG_PROPERTIES = True
