# Generated by Django 3.2 on 2023-08-25 21:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('elevaweb', '0002_remove_correo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='correo',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
